version: '3.7'

services:
  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      [ "5432:5432" ]
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: car-rent-database


  api:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      - db
